doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
          procurement_customer_id: 'App\Infrastructure\Doctrine\Type\Procurement\CustomerIdType'
          procurement_proposal_id: 'App\Infrastructure\Doctrine\Type\Procurement\ProposalIdType'
          procurement_proposal_status: 'App\Infrastructure\Doctrine\Type\Procurement\ProposalStatusType'
          procurement_request_id: 'App\Infrastructure\Doctrine\Type\Procurement\RequestIdType'
          procurement_supplier_id: 'App\Infrastructure\Doctrine\Type\Procurement\SupplierIdType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Procurement:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Procurement'
                prefix: 'App\Model\Procurement'
                alias: Procurement
